[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tailwind_solana_linked_list = "2E5C8KgHySisB4xSuh4t6rYHNXQJzKwvgpZGvK5GEP29"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
